### ISSUE TITLE
Issue when installing package

### ISSUE THREAD

**Issue by bachvtuan** [sger/go-apns2#1]
This get this error

```
sger/go-apns2/client.go:31: undefined: http2.ConfigureTransport
```

when I was installing your packge.
I'm using version 1.6.

**Comment by sger** [comment]
@bachvtuan make sure you have this package golang.org/x/net/http2 and of course Go 1.6

**Comment by bachvtuan** [comment]
I have already installed the package golang.org/x/net/http2. 
I found the reason now. It's out of date so I removed it then install again. Next I install your package perfectly.

**Comment by sger** [comment]
@bachvtuan cool

**Comment by PravinRanjan10** [comment]
You may clean and then install again:
 go clean golang.org/x/net/http2
go get golang.org/x/net/http2
